// this page is like .env but for non-sensitive and important settings.
// contain database seed values, change only before seeding

// admin table value after initialized
export const admin_is_auto_approve = true;
export const admin_auto_approve_time = 0;
export const admin_smart_door_default_pin = '000000';
export const admin_checkout_grace_period = 3;
export const admin_staff_allowed_to_approve = true;
export const admin_staff_allowed_to_force_checkout = true;
export const admin_staff_allowed_to_dismiss_call = true;
export const addons_data = [
  {
    addon: 'Extra Bed',
    price: 50000,
    borrowMaximum: 1,
    totalStock: 10,
    isActive: true,
  },
  {
    addon: 'Extra Pillow',
    price: 5000,
    borrowMaximum: 4,
    totalStock: 30,
    isActive: true,
  },
  {
    addon: 'Extra Blanket',
    price: 10000,
    borrowMaximum: 3,
    totalStock: 25,
    isActive: true,
  },
  {
    addon: 'Towel',
    price: 5000,
    borrowMaximum: 5,
    totalStock: 60,
    isActive: true,
  },
  {
    addon: 'Bath Towel',
    price: 10000,
    borrowMaximum: 3,
    totalStock: 40,
    isActive: true,
  },
  {
    addon: 'Hanger',
    price: 1000,
    borrowMaximum: 15,
    totalStock: 80,
    isActive: true,
  },
  {
    addon: 'Body Cleaning Kit',
    price: 25000,
    borrowMaximum: 5,
    totalStock: 35,
    isActive: true,
  },
  {
    addon: 'Hair Dryer',
    price: 10000,
    borrowMaximum: 1,
    totalStock: 8,
    isActive: true,
  },
  {
    addon: 'Iron & Ironing Board',
    price: 15000,
    borrowMaximum: 1,
    totalStock: 6,
    isActive: true,
  },
  {
    addon: 'Electric Kettle',
    price: 5000,
    borrowMaximum: 1,
    totalStock: 12,
    isActive: true,
  },
  {
    addon: 'Laundry Service (per kg)',
    price: 5000,
    borrowMaximum: 10,
    totalStock: 999,
    isActive: true,
  },
  {
    addon: 'Room Cleaning Service',
    price: 25000,
    borrowMaximum: 1,
    totalStock: 999,
    isActive: true,
  },
];
export const rooms_data = [
  {
    name: 'VIP Space 101',
    price: 150000,
    capacity: 4,
    addons: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    features: [
      'King Size Bed',
      'Bathroom with Bathtub & Water Heater',
      'Air Conditioning',
      'High-Speed Fiber Wifi',
      'Walk-in Closet',
      'Smart TV 55"',
      'Mini Refrigerator',
      'Work Desk & Ergonomic Chair',
      'Balcony with City View',
      'Safe Deposit Box',
    ],
  },
  {
    name: 'VIP Space 102',
    price: 150000,
    capacity: 4,
    addons: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    features: [
      'King Size Bed',
      'Bathroom with Bathtub & Water Heater',
      'Air Conditioning',
      'High-Speed Fiber Wifi',
      'Walk-in Closet',
      'Smart TV 55"',
      'Mini Refrigerator',
      'Work Desk & Ergonomic Chair',
      'Balcony with City View',
      'Safe Deposit Box',
    ],
  },
  {
    name: 'VIP Space 103',
    price: 150000,
    capacity: 4,
    addons: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    features: [
      'King Size Bed',
      'Bathroom with Bathtub & Water Heater',
      'Air Conditioning',
      'High-Speed Fiber Wifi',
      'Walk-in Closet',
      'Smart TV 55"',
      'Mini Refrigerator',
      'Work Desk & Ergonomic Chair',
      'Balcony with City View',
      'Safe Deposit Box',
    ],
  },
  {
    name: 'Golden Space 201',
    price: 100000,
    capacity: 4,
    addons: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    features: [
      'Queen Size Bed',
      'Bathroom with Water Heater',
      'Air Conditioning',
      'High-Speed Wifi',
      'Large Wardrobe',
      'Smart TV 43"',
      'Mini Fridge',
      'Study Desk & Chair',
      'Window View',
    ],
  },
  {
    name: 'Golden Space 202',
    price: 100000,
    capacity: 4,
    addons: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    features: [
      'Queen Size Bed',
      'Bathroom with Water Heater',
      'Air Conditioning',
      'High-Speed Wifi',
      'Large Wardrobe',
      'Smart TV 43"',
      'Mini Fridge',
      'Study Desk & Chair',
      'Window View',
    ],
  },
  {
    name: 'Golden Space 203',
    price: 100000,
    capacity: 4,
    addons: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    features: [
      'Queen Size Bed',
      'Bathroom with Water Heater',
      'Air Conditioning',
      'High-Speed Wifi',
      'Large Wardrobe',
      'Smart TV 43"',
      'Mini Fridge',
      'Study Desk & Chair',
      'Window View',
    ],
  },
  {
    name: 'Golden Space 204',
    price: 100000,
    capacity: 4,
    addons: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    features: [
      'Queen Size Bed',
      'Bathroom with Water Heater',
      'Air Conditioning',
      'High-Speed Wifi',
      'Large Wardrobe',
      'Smart TV 43"',
      'Mini Fridge',
      'Study Desk & Chair',
      'Window View',
    ],
  },
  {
    name: 'Golden Space 205',
    price: 100000,
    capacity: 4,
    addons: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    features: [
      'Queen Size Bed',
      'Bathroom with Water Heater',
      'Air Conditioning',
      'High-Speed Wifi',
      'Large Wardrobe',
      'Smart TV 43"',
      'Mini Fridge',
      'Study Desk & Chair',
      'Window View',
    ],
  },
  {
    name: 'Basic Space 301',
    price: 70000,
    capacity: 2,
    addons: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    features: [
      'Single Bed',
      'Private Bathroom',
      'Air Conditioning',
      'Standard Wifi',
      'Wardrobe',
      'TV 32"',
      'Small Desk',
    ],
  },
  {
    name: 'Basic Space 302',
    price: 70000,
    capacity: 2,
    addons: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    features: [
      'Single Bed',
      'Private Bathroom',
      'Air Conditioning',
      'Standard Wifi',
      'Wardrobe',
      'TV 32"',
      'Small Desk',
    ],
  },
  {
    name: 'Basic Space 303',
    price: 70000,
    capacity: 2,
    addons: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    features: [
      'Single Bed',
      'Private Bathroom',
      'Air Conditioning',
      'Standard Wifi',
      'Wardrobe',
      'TV 32"',
      'Small Desk',
    ],
  },
  {
    name: 'Basic Space 304',
    price: 70000,
    capacity: 2,
    addons: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    features: [
      'Single Bed',
      'Private Bathroom',
      'Air Conditioning',
      'Standard Wifi',
      'Wardrobe',
      'TV 32"',
      'Small Desk',
    ],
  },
  {
    name: 'Basic Space 305',
    price: 70000,
    capacity: 2,
    addons: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    features: [
      'Single Bed',
      'Private Bathroom',
      'Air Conditioning',
      'Standard Wifi',
      'Wardrobe',
      'TV 32"',
      'Small Desk',
    ],
  },
  {
    name: 'Basic Space 306',
    price: 70000,
    capacity: 2,
    addons: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    features: [
      'Single Bed',
      'Private Bathroom',
      'Air Conditioning',
      'Standard Wifi',
      'Wardrobe',
      'TV 32"',
      'Small Desk',
    ],
  },
  {
    name: 'Basic Space 307',
    price: 70000,
    capacity: 2,
    addons: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    features: [
      'Single Bed',
      'Private Bathroom',
      'Air Conditioning',
      'Standard Wifi',
      'Wardrobe',
      'TV 32"',
      'Small Desk',
    ],
  },
  {
    name: 'Student Space 401',
    price: 50000,
    capacity: 2,
    addons: [2, 3, 4, 6, 7, 10, 11, 12],
    features: [
      'Single Bed',
      'Study Desk & Chair',
      'Standing Fan',
      'Shared Bathroom',
      'Standard Wifi',
      'Wall Shelves',
      'Small Wardrobe',
    ],
  },
  {
    name: 'Student Space 402',
    price: 50000,
    capacity: 2,
    addons: [2, 3, 4, 6, 7, 10, 11, 12],
    features: [
      'Single Bed',
      'Study Desk & Chair',
      'Standing Fan',
      'Shared Bathroom',
      'Standard Wifi',
      'Wall Shelves',
      'Small Wardrobe',
    ],
  },
  {
    name: 'Student Space 403',
    price: 50000,
    capacity: 2,
    addons: [2, 3, 4, 6, 7, 10, 11, 12],
    features: [
      'Single Bed',
      'Study Desk & Chair',
      'Standing Fan',
      'Shared Bathroom',
      'Standard Wifi',
      'Wall Shelves',
      'Small Wardrobe',
    ],
  },
  {
    name: 'Student Space 404',
    price: 50000,
    capacity: 2,
    addons: [2, 3, 4, 6, 7, 10, 11, 12],
    features: [
      'Single Bed',
      'Study Desk & Chair',
      'Standing Fan',
      'Shared Bathroom',
      'Standard Wifi',
      'Wall Shelves',
      'Small Wardrobe',
    ],
  },
  {
    name: 'Student Space 405',
    price: 50000,
    capacity: 2,
    addons: [2, 3, 4, 6, 7, 10, 11, 12],
    features: [
      'Single Bed',
      'Study Desk & Chair',
      'Standing Fan',
      'Shared Bathroom',
      'Standard Wifi',
      'Wall Shelves',
      'Small Wardrobe',
    ],
  },
  {
    name: 'Student Space 406',
    price: 50000,
    capacity: 2,
    addons: [2, 3, 4, 6, 7, 10, 11, 12],
    features: [
      'Single Bed',
      'Study Desk & Chair',
      'Standing Fan',
      'Shared Bathroom',
      'Standard Wifi',
      'Wall Shelves',
      'Small Wardrobe',
    ],
  },
];
